version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/travel_db
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mongo:latest
    container_name: mongo_db
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  uploads_data:
