services:
  backend:
    build: ./backend
    container_name: fastapi_app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/travel_db
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mongo:latest
    container_name: mongo_db
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
